services:
  hellodoc-server:
    build: .
    image: hellodoc-server:latest
    container_name: hellodoc
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${SERVER_PORT:-8899}:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_SQL_INIT_MODE=never
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - FILE_UPLOAD_DIR=/app/data
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_SERVLET_CONTEXT_PATH=/
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
