spring.application.name=hellodoc
app.version=2.0.0
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hellodoc}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.session.jdbc.initialize-schema=never
spring.jpa.hibernate.ddl-auto=none
# Spring SQL Initialization (Disabled due to Hikari connection closed error)
spring.sql.init.mode=never
# spring.sql.init.schema-locations=classpath:data/hellodoc_schema.sql
# spring.sql.init.continue-on-error=true
# spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# jpa.database=postgresql
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.enabled=true
spring.config.import=classpath:sys_config.yaml

# Multipart upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
